"""Economic Value Added Module"""

__docformat__ = "google"

import pandas as pd


def get_net_operating_profit_after_taxes(
    ebit: float | pd.Series | pd.DataFrame,
    effective_tax_rate: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Net Operating Profit After Taxes (NOPAT) represents a company's theoretical operating
    profitability if it had no debt, i.e. the profit generated by core operations after
    accounting for taxes but before the cost of financing.

    The formula is as follows:

        - NOPAT = EBIT * (1 - Effective Tax Rate)

    Args:
        ebit (float | pd.Series | pd.DataFrame): The earnings before interest and taxes.
        effective_tax_rate (float | pd.Series | pd.DataFrame): The effective tax rate of the company.

    Returns:
        float | pd.Series | pd.DataFrame: The Net Operating Profit After Taxes (NOPAT).

    Notes:
    - NOPAT is a component used in the calculation of Economic Value Added (EVA) and
    Return on Invested Capital (ROIC).
    """

    return ebit * (1 - effective_tax_rate)


def get_invested_capital(
    total_equity: float | pd.Series | pd.DataFrame,
    total_debt: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Invested Capital represents the total amount of capital, both equity and debt,
    that has been invested in a company's operations.

    The formula is as follows:

        - Invested Capital = Total Equity + Total Debt

    Args:
        total_equity (float | pd.Series | pd.DataFrame): The total equity of the company.
        total_debt (float | pd.Series | pd.DataFrame): The total debt of the company.

    Returns:
        float | pd.Series | pd.DataFrame: The Invested Capital.
    """

    return total_equity + total_debt


def get_economic_value_added(
    net_operating_profit_after_taxes: float | pd.Series | pd.DataFrame,
    weighted_average_cost_of_capital: float | pd.Series | pd.DataFrame,
    invested_capital: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    Economic Value Added (EVA) is a measure of a company's financial performance that
    represents the value created in excess of the required return of the company's
    capital providers (both equity and debt holders). It captures whether a company is
    generating returns above its true cost of capital, which a purely accounting-based
    measure such as Net Income does not.

    The formula is as follows:

        - EVA = NOPAT - (Weighted Average Cost of Capital * Invested Capital)

    Also known as: EVA, economic profit.

    Args:
        net_operating_profit_after_taxes (float | pd.Series | pd.DataFrame): The Net Operating
        Profit After Taxes (NOPAT) of the company.
        weighted_average_cost_of_capital (float | pd.Series | pd.DataFrame): The weighted average
        cost of capital (WACC) of the company.
        invested_capital (float | pd.Series | pd.DataFrame): The invested capital of the company,
        i.e. the sum of total equity and total debt.

    Returns:
        float | pd.Series | pd.DataFrame: The Economic Value Added (EVA).

    Notes:
    - A positive EVA indicates that the company is generating returns in excess of its cost of
    capital, i.e. it is creating value for its capital providers.
    - A negative EVA indicates that the company is not generating enough return to cover its
    cost of capital, i.e. it is destroying value.

    References:
    - Stern, Joel M., G. Bennett Stewart, and Donald H. Chew. "The EVA Financial Management
    System." Journal of Applied Corporate Finance, Vol. 8, No. 2, 1995, pp. 32-46.
    """

    return net_operating_profit_after_taxes - (
        weighted_average_cost_of_capital * invested_capital
    )
