"""Fulmer Module"""

__docformat__ = "google"

import numpy as np
import pandas as pd

# pylint: disable=too-many-arguments,too-many-positional-arguments


def get_retained_earnings_to_total_assets_ratio(
    retained_earnings: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Retained Earnings to Total Assets Ratio (V1) is a financial metric used to measure a company's
    profitability and the proportion of its assets that are financed by its retained earnings. It is the
    first component of the Fulmer H-Score.

    The formula is as follows:

        - Retained Earnings to Total Assets Ratio = Retained Earnings / Total Assets

    Args:
        retained_earnings (float | pd.Series | pd.DataFrame): The portion of a company's net income that is
        not paid out as dividends.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Retained Earnings to Total Assets Ratio.
    """

    return retained_earnings / total_assets


def get_sales_to_total_assets_ratio(
    sales: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Sales to Total Assets Ratio (V2) is a financial metric used to measure a company's efficiency and
    the proportion of its assets that are used to generate sales. It is the second component of the Fulmer
    H-Score.

    The formula is as follows:

        - Sales to Total Assets Ratio = Sales / Total Assets

    Args:
        sales (float | pd.Series | pd.DataFrame): The revenue generated by a company.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Sales to Total Assets Ratio.
    """

    return sales / total_assets


def get_ebt_to_equity_ratio(
    ebt: float | pd.Series | pd.DataFrame,
    total_equity: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The EBT to Equity Ratio (V3) measures a company's pre-tax profitability relative to the book value of
    equity invested in it. It is the third component of the Fulmer H-Score.

    The formula is as follows:

        - EBT to Equity Ratio = Earnings Before Taxes / Total Equity

    Args:
        ebt (float | pd.Series | pd.DataFrame): Earnings before taxes (income before tax).
        total_equity (float | pd.Series | pd.DataFrame): The total equity of the company.

    Returns:
        float | pd.Series | pd.DataFrame: The EBT to Equity Ratio.
    """

    return ebt / total_equity


def get_cash_flow_to_total_liabilities_ratio(
    cash_flow: float | pd.Series | pd.DataFrame,
    total_liabilities: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Cash Flow to Total Liabilities Ratio (V4) measures a company's ability to service its total debt
    load from the cash generated by its core operations. It is the fourth component of the Fulmer H-Score.

    The formula is as follows:

        - Cash Flow to Total Liabilities Ratio = Cash Flow from Operations / Total Liabilities

    Args:
        cash_flow (float | pd.Series | pd.DataFrame): The cash flow generated by a company, typically its
        Operating Cash Flow.
        total_liabilities (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current
        liabilities.

    Returns:
        float | pd.Series | pd.DataFrame: The Cash Flow to Total Liabilities Ratio.
    """

    return cash_flow / total_liabilities


def get_debt_to_total_assets_ratio(
    total_debt: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Debt to Total Assets Ratio (V5) measures the proportion of a company's assets financed with
    interest-bearing debt. It is the fifth component of the Fulmer H-Score and, unlike V6 below, this uses
    Total Debt rather than Current Liabilities.

    The formula is as follows:

        - Debt to Total Assets Ratio = Total Debt / Total Assets

    Args:
        total_debt (float | pd.Series | pd.DataFrame): The total interest-bearing debt of the company.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Debt to Total Assets Ratio.

    Notes:
    - This is the only component of the Fulmer H-Score with a negative coefficient, i.e. higher leverage
    lowers the H-Score.
    """

    return total_debt / total_assets


def get_current_liabilities_to_total_assets_ratio(
    current_liabilities: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Current Liabilities to Total Assets Ratio (V6) measures the proportion of a company's assets that
    are financed by short-term obligations. It is the sixth component of the Fulmer H-Score.

    The formula is as follows:

        - Current Liabilities to Total Assets Ratio = Current Liabilities / Total Assets

    Args:
        current_liabilities (float | pd.Series | pd.DataFrame): The short-term liabilities of a company due
        within one year.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Current Liabilities to Total Assets Ratio.
    """

    return current_liabilities / total_assets


def get_tangible_total_assets(
    total_assets: float | pd.Series | pd.DataFrame,
    goodwill_and_intangible_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    Tangible Total Assets strips goodwill and other intangible assets out of Total Assets, leaving only the
    assets with physical substance or contractual cash claims. It is used as the basis for V7 of the Fulmer
    H-Score.

    The formula is as follows:

        - Tangible Total Assets = Total Assets - Goodwill and Intangible Assets

    Args:
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.
        goodwill_and_intangible_assets (float | pd.Series | pd.DataFrame): The goodwill and other intangible
        assets of the company.

    Returns:
        float | pd.Series | pd.DataFrame: The Tangible Total Assets.
    """

    return total_assets - goodwill_and_intangible_assets


def get_log_of_tangible_total_assets(
    tangible_total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Log of Tangible Total Assets (V7) is a proxy for firm size, using only tangible assets, in the
    Fulmer H-Score. It is the seventh component of the model.

    The formula is as follows:

        - V7 = ln(Tangible Total Assets)

    Args:
        tangible_total_assets (float | pd.Series | pd.DataFrame): The Tangible Total Assets of the company.
        See `get_tangible_total_assets`.

    Returns:
        float | pd.Series | pd.DataFrame: The Log of Tangible Total Assets.

    Notes:
    - Because this term is a natural logarithm, periods where Tangible Total Assets is zero or negative
    (e.g. a company whose Goodwill and Intangible Assets exceed its Total Assets) will produce NaN. This is
    a structural limitation of the log-linear Fulmer specification, not a bug.
    - The original Fulmer (1984) paper does not unambiguously document the log base used. This
    implementation uses the natural logarithm (base e), consistent with how the analogous SIZE term is
    handled for the Ohlson O-Score elsewhere in this module (see `get_log_of_total_assets` in the Ohlson
    module). Because the same log base is applied to every observation, this choice does not affect the
    *ranking* of companies relative to one another, only the absolute scale of V7 (and, through the 0.575
    coefficient, of the H-Score itself).
    """

    return np.log(tangible_total_assets)


def get_working_capital_to_total_liabilities_ratio(
    working_capital: float | pd.Series | pd.DataFrame,
    total_liabilities: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Working Capital to Total Liabilities Ratio (V8) measures a company's short-term liquidity relative
    to the size of its total debt load. It is the eighth component of the Fulmer H-Score.

    The formula is as follows:

        - Working Capital to Total Liabilities Ratio = Working Capital / Total Liabilities

    Args:
        working_capital (float | pd.Series | pd.DataFrame): The difference between a company's current assets
        and its current liabilities.
        total_liabilities (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current
        liabilities.

    Returns:
        float | pd.Series | pd.DataFrame: The Working Capital to Total Liabilities Ratio.
    """

    return working_capital / total_liabilities


def get_log_of_ebit_to_interest_expense_ratio(
    ebit: float | pd.Series | pd.DataFrame,
    interest_expense: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Log of the EBIT to Interest Expense Ratio (V9) is a logged interest coverage ratio, measuring a
    company's ability to meet its interest obligations out of operating earnings. It is the ninth and final
    component of the Fulmer H-Score.

    The formula is as follows:

        - V9 = ln(EBIT / Interest Expense)

    Args:
        ebit (float | pd.Series | pd.DataFrame): Earnings before interest and taxes.
        interest_expense (float | pd.Series | pd.DataFrame): The interest expense of the company.

    Returns:
        float | pd.Series | pd.DataFrame: The Log of the EBIT to Interest Expense Ratio.

    Notes:
    - Because this term is a natural logarithm, periods where EBIT and Interest Expense do not have the same
    sign (e.g. negative EBIT, or a company with no interest expense) will produce NaN or an undefined
    result. This is a structural limitation of the log-linear Fulmer specification, not a bug, and mirrors
    the same limitation documented for the Graham Number elsewhere in this toolkit.
    - See `get_log_of_tangible_total_assets` for the log base used (natural logarithm).
    """

    return np.log(ebit / interest_expense)


def get_fulmer_h_score(
    retained_earnings_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    sales_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    ebt_to_equity_ratio: float | pd.Series | pd.DataFrame,
    cash_flow_to_total_liabilities_ratio: float | pd.Series | pd.DataFrame,
    debt_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    current_liabilities_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    log_of_tangible_total_assets: float | pd.Series | pd.DataFrame,
    working_capital_to_total_liabilities_ratio: float | pd.Series | pd.DataFrame,
    log_of_ebit_to_interest_expense_ratio: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Fulmer H-Score is a financial metric, developed by Fulmer, Moon, Gavin and Erwin in 1984, used to
    measure a company's solvency and the likelihood that it will go bankrupt. Unlike the Altman Z-Score,
    which was built on a sample of relatively large, listed manufacturing companies, the Fulmer H-Score was
    specifically calibrated on a matched-pair sample of small, failed and non-failed U.S. companies (average
    asset size of roughly $455,000 at the time of the study), and uses nine financial ratios derived via
    step-wise multiple discriminant analysis from an initial pool of 40 ratios.

    The formula is as follows:

        H-Score = 5.528 * V1 + 0.212 * V2 + 0.073 * V3 + 1.270 * V4 - 0.120 * V5 + 2.335 * V6
        + 0.575 * V7 + 1.083 * V8 + 0.894 * V9 - 6.075

    The nine variables are:

        - V1: Retained Earnings to Total Assets Ratio
        - V2: Sales to Total Assets Ratio
        - V3: EBT to Equity Ratio
        - V4: Cash Flow to Total Liabilities Ratio
        - V5: Debt to Total Assets Ratio
        - V6: Current Liabilities to Total Assets Ratio
        - V7: Log of Tangible Total Assets
        - V8: Working Capital to Total Liabilities Ratio
        - V9: Log of the EBIT to Interest Expense Ratio

    Also known as: Fulmer H-Score, H factor, bankruptcy prediction, financial distress score.

    Args:
        retained_earnings_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Retained Earnings to
        Total Assets Ratio (V1).
        sales_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Sales to Total Assets Ratio (V2).
        ebt_to_equity_ratio (float | pd.Series | pd.DataFrame): The EBT to Equity Ratio (V3).
        cash_flow_to_total_liabilities_ratio (float | pd.Series | pd.DataFrame): The Cash Flow to Total
        Liabilities Ratio (V4).
        debt_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Debt to Total Assets Ratio (V5).
        current_liabilities_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Current Liabilities
        to Total Assets Ratio (V6).
        log_of_tangible_total_assets (float | pd.Series | pd.DataFrame): The Log of Tangible Total Assets (V7).
        working_capital_to_total_liabilities_ratio (float | pd.Series | pd.DataFrame): The Working Capital to
        Total Liabilities Ratio (V8).
        log_of_ebit_to_interest_expense_ratio (float | pd.Series | pd.DataFrame): The Log of the EBIT to
        Interest Expense Ratio (V9).

    Returns:
        float | pd.Series | pd.DataFrame: The Fulmer H-Score.

    Notes:
    - An H-Score of less than 0 predicts failure; an H-Score of greater than 0 predicts non-failure. In the
    original study, this classification was reported as 98% accurate on the sample used to build the model
    (and 81% accurate one year prior to failure), though as with any model of this type, out-of-sample
    accuracy on other populations of companies tends to be materially lower.
    - Because V7 (the log of Tangible Total Assets) uses an un-normalized dollar figure, the H-Score is
    sensitive to the absolute scale of a company's assets: very large companies will tend to show a
    substantially higher V7 contribution than the small firms the model was originally calibrated on, purely
    as a function of size rather than financial health. Treat H-Scores for companies far outside the small
    to mid-cap range this model was built for with additional caution.
    - As with the Altman Z-Score, Springate Score and Grover Score, this is a probabilistic, not a
    definitive, indicator and should be combined with further fundamental analysis.

    References:
    - Fulmer, John G., James E. Moon, Thomas A. Gavin, and Michael J. Erwin. "A Bankruptcy Classification
    Model for Small Firms." Journal of Commercial Bank Lending, Vol. 66, No. 11, 1984, pp. 25-37.
    """
    if not isinstance(
        retained_earnings_to_total_assets_ratio,
        int | float | pd.Series | pd.DataFrame,
    ):
        raise TypeError(
            "retained_earnings_to_total_assets_ratio must be a float, pd.Series or "
            f"pd.DataFrame, not {type(retained_earnings_to_total_assets_ratio)}."
        )

    return (
        5.528 * retained_earnings_to_total_assets_ratio
        + 0.212 * sales_to_total_assets_ratio
        + 0.073 * ebt_to_equity_ratio
        + 1.270 * cash_flow_to_total_liabilities_ratio
        - 0.120 * debt_to_total_assets_ratio
        + 2.335 * current_liabilities_to_total_assets_ratio
        + 0.575 * log_of_tangible_total_assets
        + 1.083 * working_capital_to_total_liabilities_ratio
        + 0.894 * log_of_ebit_to_interest_expense_ratio
        - 6.075
    )
