"""Springate Module"""

__docformat__ = "google"

import pandas as pd


def get_working_capital_to_total_assets_ratio(
    working_capital: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Working Capital to Total Assets Ratio is a financial metric used to measure a company's liquidity and
    ability to meet short-term obligations. It represents the proportion of a company's total assets that are
    financed by its working capital. It is the liquidity component of the Springate Score.

    The formula is as follows:

        - Working Capital to Total Assets Ratio = Working Capital / Total Assets

    Args:
        working_capital (float | pd.Series | pd.DataFrame): The difference between a company's current assets and
        its current liabilities.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Working Capital to Total Assets Ratio.

    Notes:
    - A ratio of less than 1 indicates that a company may have difficulty meeting its short-term obligations.
    """

    return working_capital / total_assets


def get_ebit_to_total_assets_ratio(
    ebit: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The EBIT to Total Assets Ratio is a financial metric used to measure a company's profitability and the
    efficiency with which it uses its assets. It is the profitability component of the Springate Score.

    The formula is as follows:

        - EBIT to Total Assets Ratio = EBIT / Total Assets

    Args:
        ebit (float | pd.Series | pd.DataFrame): Earnings before interest and taxes.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The EBIT to Total Assets Ratio.

    Notes:
    - A high ratio indicates that a company is generating a high return on its assets.
    """

    return ebit / total_assets


def get_ebt_to_current_liabilities_ratio(
    ebt: float | pd.Series | pd.DataFrame,
    current_liabilities: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The EBT to Current Liabilities Ratio is a financial metric used to measure a company's ability to cover its
    short-term obligations out of its pre-tax earnings. It is the solvency component of the Springate Score.

    The formula is as follows:

        - EBT to Current Liabilities Ratio = Earnings Before Taxes / Current Liabilities

    Args:
        ebt (float | pd.Series | pd.DataFrame): Earnings before taxes (income before tax).
        current_liabilities (float | pd.Series | pd.DataFrame): The short-term liabilities of a company due
        within one year.

    Returns:
        float | pd.Series | pd.DataFrame: The EBT to Current Liabilities Ratio.

    Notes:
    - A low (or negative) ratio indicates weak coverage of short-term liabilities out of pre-tax earnings.
    """

    return ebt / current_liabilities


def get_sales_to_total_assets_ratio(
    sales: float | pd.Series | pd.DataFrame,
    total_assets: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Sales to Total Assets Ratio is a financial metric used to measure a company's efficiency and the
    proportion of its assets that are used to generate sales. It is the efficiency component of the
    Springate Score.

    The formula is as follows:

        - Sales to Total Assets Ratio = Sales / Total Assets

    Args:
        sales (float | pd.Series | pd.DataFrame): The revenue generated by a company.
        total_assets (float | pd.Series | pd.DataFrame): The sum of a company's current and non-current assets.

    Returns:
        float | pd.Series | pd.DataFrame: The Sales to Total Assets Ratio.

    Notes:
    - A low ratio can indicate that a company is not efficiently using its assets to generate sales.
    """

    return sales / total_assets


def get_springate_score(
    working_capital_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    ebit_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
    ebt_to_current_liabilities_ratio: float | pd.Series | pd.DataFrame,
    sales_to_total_assets_ratio: float | pd.Series | pd.DataFrame,
) -> float | pd.Series | pd.DataFrame:
    """
    The Springate Score is a financial metric, developed by Gordon L.V. Springate in 1978, used to measure a
    company's solvency and the likelihood that it will go bankrupt. Springate built the model using a
    step-wise multiple discriminant analysis on 19 possible financial ratios, of which four were ultimately
    selected. It follows the same discriminant-analysis methodology as the Altman Z-Score, using a smaller,
    Canadian-firm-calibrated set of ratios.

    The formula is as follows:

        Springate Score = 1.03 * Working Capital to Total Assets Ratio + 3.07 * EBIT to Total Assets Ratio
        + 0.66 * EBT to Current Liabilities Ratio + 0.4 * Sales to Total Assets Ratio

    Also known as: Springate Score, S-Score, bankruptcy prediction, financial distress score.

    Args:
        working_capital_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Working Capital to Total
        Assets Ratio.
        ebit_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The EBIT to Total Assets Ratio.
        ebt_to_current_liabilities_ratio (float | pd.Series | pd.DataFrame): The EBT to Current Liabilities
        Ratio.
        sales_to_total_assets_ratio (float | pd.Series | pd.DataFrame): The Sales to Total Assets Ratio.

    Returns:
        float | pd.Series | pd.DataFrame: The Springate Score.

    Notes:
    - A Springate Score of less than 0.862 indicates a high likelihood of bankruptcy. In his original study,
    Springate found this cutoff correctly classified companies with over 92% accuracy on the sample used to
    build the model, though as with any model of this type, out-of-sample accuracy on other populations of
    companies (in particular companies outside of Canada or well outside the model's original size range)
    tends to be materially lower.
    - As with the Altman Z-Score, this is a probabilistic, not a definitive, indicator and should be combined
    with further fundamental analysis.

    References:
    - Springate, Gordon L.V. "Predicting the Possibility of Failure in a Canadian Firm." Unpublished M.B.A.
    Research Project, Simon Fraser University, 1978.
    """
    if not isinstance(
        working_capital_to_total_assets_ratio, int | float | pd.Series | pd.DataFrame
    ):
        raise TypeError(
            "working_capital_to_total_assets_ratio must be a float, pd.Series or "
            f"pd.DataFrame, not {type(working_capital_to_total_assets_ratio)}."
        )

    return (
        1.03 * working_capital_to_total_assets_ratio
        + 3.07 * ebit_to_total_assets_ratio
        + 0.66 * ebt_to_current_liabilities_ratio
        + 0.4 * sales_to_total_assets_ratio
    )
